[build]
  publish = "public"  # Asegúrate de que este directorio tenga tu archivo index.html
  functions = "functions"  # Donde están tus funciones Netlify

[[redirects]]
  from = "/api/*"  # Redirige las solicitudes API a las funciones de Netlify
  to = "/.netlify/functions/:splat"
  status = 200